name: cobaya-minuit-tutorial
channels:
  - conda-forge
dependencies:
  - matplotlib
  - pip:
      - cobaya
      - iminuit
      - git+https://github.com/xgarrido/cobaya-minuit-sampler.git#egg=cobaya-minuit-sampler
