#+TITLE: SN@ilWare simulations : comparison between legacy and development branch

* Introduction

Since the switch to the new Cadfael/Bayeux/Falaise software suite, some time
latency has been found when simulating SuperNEMO events. For instance,
simulating 2\beta events on Lyon cluster was taking 20 minutes for 10 000 events
when it takes now more than 2 hours.

The purpose of this note is to investigate where the time processing is going by
comparing on a basic simulation setup the =legacy= code with the =trunk=
development branch.

* Installation of =legacy= branch

** Cadfael
To install the =legacy= branch, we use the =aggregator= script file and its
latest [[ https://github.com/xgarrido/zsh-aggregator/commit/1b2ed677e83e3548fa6812c19f1e4240adbdf6a7][revision]] to get Cadfael legacy version. This will install Cadfael within
=~/Workdir/NEMO/supernemo/development= directory for the following software
versions :

- GSL version 1.16
- Xerces-C version 3.1.1
- CAMP version 0.7.1
- CLHEP version 2.1.3.1
- Geant4 version 9.6p01
- Boost version 1.55.0
- ROOT version 5.34.14

In order to properly setup Cadfael components, do
#+BEGIN_SRC sh
  aggregator setup cadfael
#+END_SRC

*You must be sure to run the =master= branch of the =aggregator= script,
otherwise it will setup the new Cadfael configuration*
** Bayeux
To setup Bayeux as a standalone library, you should use the =snailware= script
and do
#+BEGIN_SRC sh
  snailware setup bayeux
#+END_SRC
* Simulation setup
For comparison we will use a very simple setup that we will work for both
software version. The setup is stored [[https://github.com/xgarrido/bayeux_simulation_modules/tree/master/geant4_validation][here]] : it defines a very basic geometry
setup with a gas volume + a scintillator material. On this machine, the setup is
installed
=~/Workdir/NEMO/supernemo/simulations/bayeux_simulation_modules/geant4_validation=
directory. Given the module + simulation setup have been installed, the
processing is done by
#+BEGIN_SRC sh
  dpp_processing                                                                                                                                   \
      --dlls-config ~/Workdir/NEMO/supernemo/simulations/bayeux_simulation_modules/geant4_validation/config/pipeline/dlls.conf                     \
      -l geomtools -l mctools_g4                                                                                                                   \
      --module-manager-config ~/Workdir/NEMO/supernemo/simulations/bayeux_simulation_modules/geant4_validation/config/pipeline/module_manager.conf \
      --module geant4_simulation_module                                                                                                            \
      -M 100 --logging-priority trace
#+END_SRC
