#+TITLE: Steven's thesis booknotes
#+DESCRIPTION: Notes relative to Steven Calvez's PhD thesis
#+OPTIONS: toc:1

* DONE SN@ilWare simulation @ Lyon                               :28_09_2014:
CLOSED: [2014-10-01 mer. 22:52]

** DONE Simulation enhancements
CLOSED: [2014-09-30 mar. 16:42]

Generate signal & backgrounds simulations for SuperNEMO demonstrator after
having updated the following points :

- [X] remove events with two much unclustered hits from =CAT= clustering
  algorithm (see [[https://github.com/xgarrido/snemo_simulation_configuration/commit/5839ed54d4d47ac2c700922004139750b2a9c790][commit 5839ed]])
- [X] correct energy resolution and energy thresholds for calorimeter blocks in
  =mock_calorimeter_s2c_module= (see [[https://github.com/xgarrido/snemo_simulation_configuration/commit/41a4e035ff5e8d06c4e00f107987f5a70019f55a][commit 41a4e0]])
- [X] implement vertex generator for Radon within tracker using latest
  developement of François (see [[https://nemo.lpc-caen.in2p3.fr/changeset/15140/genvtx/trunk][changeset 15140]] & [[https://nemo.lpc-caen.in2p3.fr/changeset/15244][changeset 15140]]) : implemented
  in [[https://github.com/xgarrido/snemo_simulation_configuration/commit/49f94fadb4e62f9cb1a566c05d9ce0bce899b79b][commit 49f94f]]

** DONE Simulation set
CLOSED: [2014-10-01 mer. 22:52]

|------------------+------------------+---------+------------|
| Isotope          | Number of events | Origin  | Status     |
|------------------+------------------+---------+------------|
| 0\nu             |             10^5 | foil    | \checkmark |
| 2\nu (E > 2 MeV) |             10^7 | foil    | \checkmark |
| 2\nu (\forall E) |           > 10^7 | foil    |            |
| \nbsp^{208}Tl    |             10^7 | foil    | \checkmark |
| \nbsp^{214}Bi    |             10^7 | foil    | \checkmark |
| \nbsp^{214}Bi    |             10^7 | tracker | \checkmark |
|------------------+------------------+---------+------------|

* Analysis meeting                                               :01_10_2014:

Present : SC, MB, FM, XG

** Summary

Steven first reminds results obtained during his training period basically the
sensitivity of SuperNEMO demonstrator for\nbsp^{82}Se in 2.5 years. Simulations
include\nbsp^{214}Bi and\nbsp^{208}Tl events due to *source foil
contamination*. The presentation then focused on new background simulations of
Radon in the tracking chamber. The set of events were simulated on the surface
of *tracker field wires* given that daughter nuclei from Radon decay are
positevely charged and then deposit on the surface of ground wires /i.e./ field
wires. The study shows that a lot of 2\beta events are actually selected. Then,
Steven shows that applying new cuts on vertex position and time-of-flight (TOF)
may removed up to 63% of the Radon contamination.

** Discussion

The distribution of the internal probability exhibits a peak closed to 0 value
for 2\beta events from the source foil. These events must have been well
reconstructed from the TOF point of view. Visualization does not show any
particular features for these events and energy distribution or \chi^2 of
tracking fit are pretty closed to distribution from "good-events".

For the time being, it is not understood why these nice-looking events do not
have a "good" \chi^2 probability. It may be due to underestimation of the TOF
uncertainties especially the track length uncertainty that are currently not
taken into account. The calculation shows that the time error from track length
estimation may be arround 50 ps which is much less than the ~100-200 ps error
from calorimeter timing. Nevertheless this uncertainty coupled to the energy
error + timing resolution that finally give a better estimation to time
uncertainty when calculating TOF probability. This will need further
investigation.

Regarding cut selection for Radon events, MB suggests to also have a look on the
angular distribution of the 2 electrons that may differ between 0\nu events and
Radon.

** TODO To be done

- [ ] following Mathieu's suggestion, to have a look on the angular distribution
  of electrons,
- [ ] given the efficiency curve, estimate the number of events coming from
  Radon contamination given the required activity ~150 µBq/m^3. The tracker
  volume must be checked but it should be less than 20 m^3
- [ ] determine the new sensitivity after having applied the new vertex position
  cuts and the TOF selection
* Analysis discussion                                            :03_10_2014:

Studying E_{min} /vs./ E_{max} plot for Radon decay, Steven actually found a
large fraction of 2\beta events with same E_{min} and E_{max}. After checking,
it appears that these events had a non associated calorimeter corresponding to a
\gamma. Since only 2 calorimeter blocks was required, the 2\beta were
extrapolated within the same block : 2 electrons, 1 energy value.

We implement then a new cut that only keep event with no non-associated
calorimeter /i.e./ no \gamma in the event. [[https://nemo.lpc-caen.in2p3.fr/changeset/15256][Changeset 15256]] and [[https://github.com/xgarrido/snemo_simulation_configuration/commit/f5059b29a84e890ff1605b014fe04b12e74cd5d5][commit f5059b]]
implements and applies respectively this new selection.

* Analysis discussion                                            :10_10_2014:

During LAL/NEMO group meeting, Laurent asked if delayed Geiger cells were taken
into account in the cut selection, especially for\nbsp^{222}Rn studies. I didn't
get that in NEMO3 that even a sole delayed Geiger cell in the vicinity of the
reconstructed vertex was enough to tag the event as\nbsp^{222}Rn decay. Since
SuperNEMO trigger strategy must be the same as NEMO3, these events must be well
built when detached triggers will rise. Steven checks visually how many events
with a delayed alpha particle were found in a small set of 2\beta selected
events from\nbsp^{222}Rn. It appears that this number was not *negligible at
all*. Since the cut may only occur at calibration step, a new cut on
=calibrated_data= was implemented to remove tracker hit given a trait bits (see
[[https://nemo.lpc-caen.in2p3.fr/browser/Falaise/trunk/source/falaise/snemo/datamodels/calibrated_tracker_hit.h#L40][=calibrated_tracker_hit=]] class declaration for the bits definition).


** DONE Simulation set
CLOSED: [2014-10-14 mar. 08:39]

|------------------+------------------+-------------+------------|
| Isotope          | Number of events | Origin      | Status     |
|------------------+------------------+-------------+------------|
| 0\nu             |             10^5 | foil        | \checkmark |
| 2\nu (E > 2 MeV) |             10^6 | foil        | \checkmark |
| 2\nu (\forall E) |           > 10^7 | foil        | --         |
| \nbsp^{208}Tl    |             10^7 | foil        | \checkmark |
| \nbsp^{214}Bi    |             10^7 | foil        | \checkmark |
| \nbsp^{222}Rn    |             10^8 | field wires | \checkmark |
| \nbsp^{222}Rn    |             10^8 | tracker gas | \checkmark |
|------------------+------------------+-------------+------------|
